### ISSUE TITLE
Colorization issues

### ISSUE THREAD

**Issue by Danp2** [loganch/AutoIt-VSCode#120]
- "vscode-autoit-output-pink" is defined twice in `package.json`
- `"match": "^(#[0-9]+: | {4,})?(.*\\t([0-9]+)\\s.*)"` from `vscode-autoit-output.tmLanguage.json` causes any line with a number preceded by a tab to be colored pink.  That makes the output from both of these lines pink, which isn't desirable IMO --

```autoit
Consolewrite("Port:	4444" & @CRLF)
Consolewrite("	123" & @CRLF)
```

First item is an easy fix. @vanowm Thoughts on the 2nd item?

**Comment by vanowm** [comment]
I'm trying to understand how TextMate grammar works, the proposed update fixes this issue, however it introduced other issues, because some regexes supposed to only match beginning of the line, however `^` sign doesn't work when time/process id is shown. Hopefully someone at [stackoverflow](https://stackoverflow.com/questions/73927904/match-beginning-of-a-line-and-beginning-of-remain-line) will give some pointers.
