### ISSUE TITLE
Macros arent getting colored anymore?

### ISSUE THREAD

**Issue by Sharrq** [loganch/AutoIt-VSCode#40]
I noticed in one of the newer updates that the AutoIt Macros arent getting colored anymore. Was this done on purpose?

![image](https://user-images.githubusercontent.com/1304554/52373007-3dc23000-2a1f-11e9-8c97-8e88e5f80866.png)

**Comment by loganch** [comment]
Looked into this quickly and it seems that at some point, some themes no longer provide a color for the "constant.other" TMlanguage tag. It's weird not only because I'm not sure when it happened and I don't recall reading an update that changed any API for it, but it looks like maybe the default VSCode themes don't support while those provided by extensions are more likely to.

**Comment by loganch** [comment]
@Sharrq have you tried other themes and/or seen the differences I see?

**Comment by Sharrq** [comment]
I have not. im using the default vscode theme (i never installed a theme). But ill try one and see if it works.

**Comment by Sharrq** [comment]
Yea if i install a theme it colors them.

**Comment by loganch** [comment]
Thanks for confirming, I'll mark this as closed.
